### ISSUE TITLE
Posts on Project-Public-Page

### ISSUE THREAD

**Issue by Arcadeuh** [shareYourProject/front-end#110]
I can't get the posts of a project to show them on Project-Public-Page
```
<h2>Posts</h2>
 <div class="card" *ngFor="let post of project.posts">
         <h4 class="card-title">{{post.author.username}}</h4>
          <p class="card-text">{{post.content}}</p>
           <p>a test</p>
</div>
```
Her's a picture of what it gives : 
![image](https://user-images.githubusercontent.com/47535482/82913420-9009c600-9f6e-11ea-8cc5-57a7cd8c488c.png)

**Comment by baanloh** [comment]
API refactoring make this issue deprecated.
