### ISSUE TITLE
Problem of compilation on PostPage branch

### ISSUE THREAD

**Issue by Arcadeuh** [shareYourProject/front-end#63]
I can't "ng serve" the project on PostPage branch. It says this
![image](https://user-images.githubusercontent.com/47535482/81862669-54343100-956a-11ea-9474-9db6383d6548.png)

And I think I can fix it. Because in Post.ts, the variable for comments is called "private readonly _comments".
First I have to rename, on post-page.component.ts, "comments" to "_comments", and then make it protected, instead of private.

I'm not sure about this correction. Sould I let you fix it ?

**Comment by baanloh** [comment]
Let me fix API related issue. It will be fixed tomorrow.
