### ISSUE TITLE
Getting the project in Project-Public-Page.html

### ISSUE THREAD

**Issue by Arcadeuh** [shareYourProject/front-end#66]
On Project-Public-Page, I try to get the variable "project" with this line :
<div class="container" *ngIf="(project$ | async) as project; else loading">
With project$ a Promise : project$: Promise<Project>

But every time I do "ng serve", it takes me to the "loading" part of the code. So I suppose the code never get the "project".

What is the problem ?

**Comment by baanloh** [comment]
Work fine. Use this route : `/project/0`.
btw, OPEN 👏  THE 👏 FUCKING 👏 CONSOLE 👏 
```
ERROR Error: "Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":404,"statusText":"Not Found","url":"http://localhost:4200/api/v1/project/1","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:4200/api/v1/project/1: 404 Not Found","error":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /api/v1/project/1</pre>\n</body>\n</html>\n"}"
```
It's clearly explain that the error is due to a 404 http response.
