### ISSUE TITLE
Difficulties to show links from "project"

### ISSUE THREAD

**Issue by Arcadeuh** [shareYourProject/front-end#68]
In Project-PublicPage, I try to show links with these lines :

```
<h2>Links</h2>
<div *ngFor="let l of project.links | keyvalue">
    <ul class="list-group list-group-flush">
         <a [href]="l.value" class="list-group-item">{{l.key}}</a>
    </ul>
</div>
```

But it's never showed in my browser : 
![image](https://user-images.githubusercontent.com/47535482/82121077-be2b2100-978a-11ea-9255-ce4ff04d52b1.png)
And I have no error in my console : 
![image](https://user-images.githubusercontent.com/47535482/82121112-f6cafa80-978a-11ea-9100-2d578ec018cb.png)

And I saw that there is the values in the Fake Back-end.
What's the problem ?

**Comment by baanloh** [comment]
Use this : `<app-links-list [links]="project.links"></app-links-list>`

**Comment by Arcadeuh** [comment]
That gives me the same thing : nothing...
![image](https://user-images.githubusercontent.com/47535482/82124546-f6892a00-979f-11ea-9505-98c85f8cd25f.png)

`<div class="col-md-3">
                <app-links-list [links]="project.links"></app-links-list>
            </div>`

**Comment by baanloh** [comment]
I have replace your lorem ipsum placeholder for members by the `user-list` component and it solve the link issue. But I don't know how ¯\_(ツ)_/¯
