### ISSUE TITLE
Can't load the post

### ISSUE THREAD

**Issue by Arcadeuh** [shareYourProject/front-end#69]
On Post-Page, I try to get the post, but I can't
For now, it shows me no error, but this : 
![image](https://user-images.githubusercontent.com/47535482/82125868-238e0a80-97a9-11ea-978c-b072a6b132e9.png)

What's the problem ? ^^'

**Comment by baanloh** [comment]
Fixed.
There is 2 routes:
- `project/0/post/0` with no comment, so 'load more' button cause a 404 error (that's normal)
- `project/0/post/1` with up to 7 comment. Trying to load more cause a 404 error (that's also normal)
