### ISSUE TITLE
Getting posts in Project-Public-Page

### ISSUE THREAD

**Issue by Arcadeuh** [shareYourProject/front-end#73]
I try to get posts of a project :
```
<div class="card" *ngFor="let post of project.posts">
       <h4 class="card-title">{{post.author.username}}</h4>
       <p class="card-text">{{post.content}}</p>
       <p>a test</p>
</div>
```

And it shows me nothing, even the `<p>a test</p>`
I suppose that I don't access posts

![image](https://user-images.githubusercontent.com/47535482/82236600-a0012480-9934-11ea-80e5-08f6ae46bf02.png)

**Comment by baanloh** [comment]
TODO: add a fetch method to Collections

**Comment by baanloh** [comment]
Solved with API refactoring
