### ISSUE TITLE
Problème de type

### ISSUE THREAD

**Issue by Arcadeuh** [shareYourProject/front-end#8]
![image](https://user-images.githubusercontent.com/47535482/80914405-9760f980-8d4b-11ea-96a8-a34009b164ec.png)
Ce que j'aimerais faire, c'est simplement push la variable i (le nom d'un des arguments, de type String) dans la liste de String "header", et il me dit qu'il y a une erreur de type
Comment je peux résoudre cela ? ^^'

**Comment by baanloh** [comment]
1. Give meaningful name to your variable. `i` is reserve for iteration.
2. In typescript never use `String`, `Number` etc... Always use `string`, `number`, etc ...
3. Need context to resolve a problem. Describe what you tried to do.

**Comment by Arcadeuh** [comment]
I've found my problem
Thank you
